name: Deploy Laravel

on:
  push: 
    branches:
    - main

jobs:
  create-deployment-artifacts:
    name: Deploy Laravel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and JS files
        run: |
              npm install
              npm run dev