name: Deploy Laravel

on:
  push: 
    branches:
    - main

jobs:
  create-deployment-artifacts:
    name: Deploy Laravel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and JS files
        run: |
              npm install
              npm run build

      - name: Configure PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2.4
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

       - name: Composer install
        run: |
              composer install --no-dev --no-interaction --prefer-dist